spring.application.name=ratingService
server.port=8083

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/hotelManagement
spring.jpa.properties.hibernate.default_schema=ratingschema
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
